name: My First Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Welcome Mwssage
      run: echo "Welcome, Obinna"

    - name: List Files
      run: ls

    - name: Read File
      run: cat README.md